---
- hosts: all
  become: yes
  tasks:
    - name: Update ArchLinux
      ansible.builtin.package:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Archlinux"

    - name: Update Debian
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
